apiVersion: v1
kind: Namespace
metadata:
  name: homesite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homesite
  namespace: homesite
  labels:
    app: homesite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homesite
  template:
    metadata:
      labels:
        app: homesite
    spec:
      containers:
      - name: homesite
        image: swilliamx/homesite:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: homesite
  namespace: homesite
  labels:
    app: homesite
  annotations:
    external-dns.alpha.kubernetes.io/hostname: homesite.mabelinc.com
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: homesite

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homesite
  namespace: homesite
  annotations:
    kubernetes.io/ingress.class: nginx
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: homesite.mabelinc.com
spec:
  ingressClassName: nginx
  rules:
    - host: homesite.mabelinc.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homesite
              port:
                number: 80